Repository dcanadillas-kube/environment-dc-jenkins-x-dev, pull requests merged in 2019-10, with the labels that each got.

#1 chore(config): update configuration
  env/parameters.yaml
  jenkins-x.yml
  jx-requirements.yml
Labels: jx/boot

#2 Add jx-app-ui 0.0.59
  env/jx-app-ui/README.MD
  env/jx-app-ui/templates/app.yaml
  env/jx-app-ui/values.yaml
  env/requirements.yaml
Labels: size/M

#3 Delete jx-app-ui
  env/requirements.yaml
Labels: size/XS

#4 Add jx-app-ui 0.0.68
  env/jx-app-ui/README.MD
  env/jx-app-ui/templates/app.yaml
  env/requirements.yaml
Labels: size/XS
